apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: spring-boot-app-manifests
    repoURL: https://github.com/Spoorthi-p-m/CICD-End-to-end
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
